name: Build

on: pull_request

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: installing dependencies
        run: npm ci
      - name: testing and building
        run: npm run build
