name: Deployment

on:
  push:
    branches: [master, beta]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Installing dependencies
        run: npm ci

      - name: Execute unit tests
        run: npm test

      - name: Building library
        run: npm run build:lib

      - name: Preparing to publish
        run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: npm run release
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: publish coverage
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lib/coverage/lcov.info
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          